version: "3"

services:
  webapp:
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9999:9999"
    volumes:
      - ".:/app"
      - "libs:/root/.ivy2/cache"
    tty: true

volumes:
  libs:
