version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
      - 9001:9001
      - 9999:9999
    volumes:
      - .:/app
      - ~/.cache/docker/.ivy2/cache:/root/.ivy2/cache
    tty: true

